# Generated by Django 3.0.5 on 2024-04-10 18:17

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_poll_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
