# Generated by Django 3.0.5 on 2024-04-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20240410_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
